//! Turnkey Client to interact with the Turnkey API
//! See <https://docs.turnkey.com>
use crate::TurnkeyClient;
use crate::generated::services::coordinator::public::v1::{COORDINATOR_SERVICE_IMPORT_PLACEHOLDER};
use crate::generated::external::activity::v1::{ACTIVITY_IMPORT_PLACEHOLDER};

use reqwest;
use tkhq_api_key_stamper::TurnkeyApiKey;
use tkhq_api_key_stamper::{stamp,TurnkeyApiKey};

// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
// This client is autogenerated. Please do not edit it manually
// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

impl TurnkeyClient {
    // <GENERATED_METHODS_PLACEHOLDER>
}
