//! Turnkey Client to interact with the Turnkey API
//! See <https://docs.turnkey.com>
use crate::{TurnkeyClient, TurnkeyClientError, Stamp};
use crate::generated::services::coordinator::public::v1 as coordinator;
use crate::generated::external::activity::v1 as external_activity;
use crate::generated::immutable::activity::v1 as immutable_activity;

// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
// This client is autogenerated. Please do not edit it manually
// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

impl<S: Stamp> TurnkeyClient<S> {
// <GENERATED_METHODS_PLACEHOLDER>
}
