[package]
name = "tvc"
version = "0.15.0"
edition = "2024"
license = "Apache-2.0"
description = "CLI for Turnkey Verifiable Cloud"
repository = "https://github.com/tkhq/rust-sdk"
homepage = "https://turnkey.com"
readme = "README.md"
documentation = "https://docs.rs/tvc"
keywords = ["turnkey", "tvc", "enclaves", "cli"]
categories = ["command-line-utilities", "cryptography"]

[lints.clippy]
mod_module_files = "deny"

[dependencies]
qos_client = { workspace = true }
qos_core = { workspace = true }
qos_crypto = { workspace = true }
qos_nsm = { workspace = true }
qos_p256 = { workspace = true }
turnkey_api_key_stamper = { workspace = true }
turnkey_client = { workspace = true }
turnkey_enclave_encrypt = { workspace = true }

anyhow = { workspace = true }
anstyle = { workspace = true }
aws-nitro-enclaves-nsm-api = { workspace = true }
base64 = { workspace = true }
borsh = { workspace = true }
chrono = { workspace = true }
clap = { workspace = true, features = ["env"] }
hex = { workspace = true }
indexmap = { workspace = true }
inquire = { workspace = true }
itertools = { workspace = true }
p256 = { workspace = true }
rand_core = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_with = { workspace = true }
thiserror = { workspace = true }
toml = { workspace = true }
tokio = { workspace = true, features = ["fs", "io-util", "rt"] }
uuid = { workspace = true }
x509-cert = { workspace = true, features = ["builder", "hazmat"] }
zeroize = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
displaydoc = { workspace = true }

[dev-dependencies]
assert_cmd = { workspace = true }
hpke = { workspace = true }
# The software ECDH in the yubikey device fake.
p256 = { workspace = true, features = ["ecdh"] }
predicates = { workspace = true }
qos_nsm = { workspace = true, features = ["mock"] }
rexpect = { workspace = true }
strum = { workspace = true }
tempfile = { workspace = true }
wiremock = { workspace = true }
