// Protos representing the update of a payment method

syntax = "proto3";

// buf:lint:ignore PACKAGE_VERSION_SUFFIX
package immutable.activity.billing;

import "vendor/google/api/field_behavior.proto";
import "vendor/protoc-gen-openapiv2/options/annotations.proto";

option go_package = "github.com/tkhq/mono/src/go/gen/pkg/immutable/activity/billing";

message UpdatePaymentMethodIntent {
  // @inject_tag: validate:"required,email,tk_email"
  string payment_email = 1 [
    (google.api.field_behavior) = REQUIRED,
    (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {
      description: "The email that will receive invoices for the payment method."
      title: ""
    }
  ];
}

message UpdatePaymentMethodResult {
  string payment_email = 1 [
    (google.api.field_behavior) = REQUIRED,
    (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {description: "The email address associated with the payment method."}
  ];
}
